---
- name: Save program outputs to a local file
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - wget
          - sysbench
          - fio
          - speedtest-cli
        state: present
        update_cache: yes

    - name: Download and extract Geekbench
      ansible.builtin.shell: |
        wget https://cdn.geekbench.com/Geekbench-5.3.1-Linux.tar.gz
        tar xf Geekbench-5.3.1-Linux.tar.gz
      args:
        creates: Geekbench-5.3.1-Linux

    - name: Run Geekbench
      ansible.builtin.command: ./Geekbench-5.3.1-Linux/geekbench5
      register: geekbench_output

    - name: Run sysbench memory tests
      ansible.builtin.shell: sysbench --test=memory --memory-block-size=1M --memory-total-size=10G run
      register: sysbench_memory_output

    - name: Run sysbench memory read tests
      ansible.builtin.shell: sysbench --test=memory --memory-block-size=1M --memory-total-size=10G --memory-oper=read run
      register: sysbench_memory_read_output

    - name: Run fio random read write test
      ansible.builtin.shell: fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=test --filename=random_read_write.fio --bs=4k --iodepth=64 --size=250M --readwrite=randrw --rwmixread=80
      register: fio_output

    - name: Run speedtest
      ansible.builtin.command: speedtest
      register: speedtest_output

    - name: Combine command outputs for CSV
      ansible.builtin.set_fact:
        combined_output_csv: |
          IP,"{{ ansible_default_ipv4.address }}"
          CPU,"{{ geekbench_output.stdout }}"
          RAM READ,"{{ sysbench_memory_output.stdout }}"
          RAM WRITE,"{{ sysbench_memory_read_output.stdout }}"
          Disk,"{{ fio_output.stdout }}"
          NET,"{{ speedtest_output.stdout }}"

    - name: Save the command outputs to a local file with current timestamp
      delegate_to: localhost
      ansible.builtin.copy:
        content: "{{ combined_output_csv }}"
        dest: "./bench_data/bench_data_{{ansible_date_time.iso8601_basic_short}}.csv"

    - name: Append the command outputs to a global file
      delegate_to: localhost
      ansible.builtin.shell: |
        echo "{{ combined_output_csv }}" >> ./bench_data/global_bench_data.csv
...
